language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install: "pip install -r requirements.txt --use-mirrors"

script: nosetests

services:
  - redis-server

before_script:
  - psql -c 'create database schedule;' -U postgres
